extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  kafka:
    topic: otlp_traces
    brokers:
    - broker-0.kafka.kafka.svc.alt.intranet:9093
    - broker-1.kafka.kafka.svc.alt.intranet:9093
    - broker-2.kafka.kafka.svc.alt.intranet:9093
    auth:
      tls:
        insecure_skip_verify: true
      scram:
        username: alt
        password: alt
        algorithm: sha512
  logging:
    logLevel: debug

service:

  pipelines:

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,kafka]
#    traces:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [logging,kafka]
